import type { Metadata } from 'next';
import { Albert_Sans } from 'next/font/google';
import '../styles/globals.css';

const albert = Albert_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={albert.className}>
        <main className="m-auto flex min-h-screen max-w-xl flex-col items-center justify-between pt-10 text-slate-700 text-sm">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
